name: CI

on: [push]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Check Code Quality
        run: pnpm run lint

      - name: Run Unit Tests
        run: pnpm run test

  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Build App
        run: pnpm run build

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: Build result
          path: dist
          retention-days: 7
